name       : supercollider
version    : 3.8.0
release    : 1
source     :
    - git|https://github.com/supercollider/supercollider : Version-3.9.3
license    : GPL-3.0
component  : multimedia.audio
summary    : An audio server, programming language, and IDE for sound synthesis and algorithmic composition
description: |
    An audio server, programming language, and IDE for sound synthesis and algorithmic composition
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-core)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sndfile)
    - pkgconfig(xt)
    - pkgconfig(yaml-cpp)
    - libboost-devel
setup      : |
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=64 \
           -DSC_EL=no \
           -DSYSTEM_BOOST=1 \
           -DSYSTEM_YAMLCPP=1 \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
