name       : supercollider
version    : 3.11.2
release    : 7
source     :
    - git|https://github.com/supercollider/supercollider : Version-3.11.2
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An audio server, programming language, and IDE for sound synthesis and
    algorithmic composition
description: |
    An audio server, programming language, and IDE for sound synthesis and algorithmic composition
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(alsa)
    - pkgconfig(avahi-core)
    - pkgconfig(fftw3)
    - pkgconfig(jack)
    - pkgconfig(sndfile)
    - pkgconfig(xt)
    - pkgconfig(yaml-cpp)
    - libboost-devel
setup      : |
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=64 \
           -DSC_EL=no \
           -DSYSTEM_BOOST=1 \
           -DSYSTEM_YAMLCPP=1 \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
